//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureProject.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LifeSureDbEntities1 : DbContext
    {
        public LifeSureDbEntities1()
            : base("name=LifeSureDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbout> TblAbout { get; set; }
        public virtual DbSet<TblAboutBox> TblAboutBox { get; set; }
        public virtual DbSet<TblCarousel> TblCarousel { get; set; }
        public virtual DbSet<TblContact> TblContact { get; set; }
        public virtual DbSet<TblFAQ> TblFAQ { get; set; }
        public virtual DbSet<TblFeature> TblFeature { get; set; }
        public virtual DbSet<TblFeatureBox> TblFeatureBox { get; set; }
        public virtual DbSet<TblService> TblService { get; set; }
        public virtual DbSet<TblServiceBox> TblServiceBox { get; set; }
        public virtual DbSet<TblTeam> TblTeam { get; set; }
        public virtual DbSet<TblTeamBox> TblTeamBox { get; set; }
        public virtual DbSet<TblTestimonial> TblTestimonial { get; set; }
        public virtual DbSet<TblTestimonialBox> TblTestimonialBox { get; set; }
    }
}
