//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureProject.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAboutBox
    {
        public int AboutBoxID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
