//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureProject.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeSureProject.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeSure Hakkında.
        /// </summary>
        public static string AboutOurCompany {
            get {
                return ResourceManager.GetString("AboutOurCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmanlarımızı Arayın.
        /// </summary>
        public static string CalltoOurExperts {
            get {
                return ResourceManager.GetString("CalltoOurExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeSure Sık Sorulan Sorular.
        /// </summary>
        public static string CommonFAQ {
            get {
                return ResourceManager.GetString("CommonFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta adresini girin.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Ara.
        /// </summary>
        public static string FindLocation {
            get {
                return ResourceManager.GetString("FindLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücretsiz.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Alın.
        /// </summary>
        public static string GetQuote {
            get {
                return ResourceManager.GetString("GetQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnaSayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esnek Hayat Sigortası.
        /// </summary>
        public static string InsuranceFlexible {
            get {
                return ResourceManager.GetString("InsuranceFlexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigortacılık güven ve yetenek gerektiren bir iştir..
        /// </summary>
        public static string InsuranceTtrustAndSkill {
            get {
                return ResourceManager.GetString("InsuranceTtrustAndSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi edinin.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkler.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta Gönder.
        /// </summary>
        public static string MailUs {
            get {
                return ResourceManager.GetString("MailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla Bilgi.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla Servis.
        /// </summary>
        public static string MoreService {
            get {
                return ResourceManager.GetString("MoreService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bülten.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bültene abone olmak için kayıt girin..
        /// </summary>
        public static string NewsletterMessage {
            get {
                return ResourceManager.GetString("NewsletterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özelliklerimiz.
        /// </summary>
        public static string OurFeatures {
            get {
                return ResourceManager.GetString("OurFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Sayfa.
        /// </summary>
        public static string Page404 {
            get {
                return ResourceManager.GetString("Page404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İyi Üretim ve Ürünler.
        /// </summary>
        public static string ProductionGood {
            get {
                return ResourceManager.GetString("ProductionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını Oku.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arancak Kelimeyi Girin.
        /// </summary>
        public static string SearchByKeyword {
            get {
                return ResourceManager.GetString("SearchByKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servislerimiz.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sık Gelen Sorular.
        /// </summary>
        public static string SomeImportantFAQ {
            get {
                return ResourceManager.GetString("SomeImportantFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekibimiz.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans.
        /// </summary>
        public static string Testimonial {
            get {
                return ResourceManager.GetString("Testimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoyu izle.
        /// </summary>
        public static string WatchVideo {
            get {
                return ResourceManager.GetString("WatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paranız Güvende.
        /// </summary>
        public static string WeCanSaveYourMoney {
            get {
                return ResourceManager.GetString("WeCanSaveYourMoney", resourceCulture);
            }
        }
    }
}
